/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace.impl;

import ac.soton.java.whitespace.whiteSpace.Discard;
import ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Discard</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DiscardImpl extends StackManipulationImpl implements Discard
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DiscardImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WhiteSpacePackage.Literals.DISCARD;
  }

} //DiscardImpl
