/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace.impl;

import ac.soton.java.whitespace.whiteSpace.StackManipulation;
import ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Stack Manipulation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StackManipulationImpl extends StatementImpl implements StackManipulation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StackManipulationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WhiteSpacePackage.Literals.STACK_MANIPULATION;
  }

} //StackManipulationImpl
