/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace.impl;

import ac.soton.java.whitespace.whiteSpace.Statement;
import ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StatementImpl extends MinimalEObjectImpl.Container implements Statement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WhiteSpacePackage.Literals.STATEMENT;
  }

} //StatementImpl
