/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace.impl;

import ac.soton.java.whitespace.whiteSpace.Swap;
import ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Swap</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SwapImpl extends StackManipulationImpl implements Swap
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SwapImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WhiteSpacePackage.Literals.SWAP;
  }

} //SwapImpl
