/*
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.ui.tests;

import ac.soton.java.whitespace.ui.internal.WhitespaceActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class WhiteSpaceUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WhitespaceActivator.getInstance().getInjector("ac.soton.java.whitespace.WhiteSpace");
	}

}
