/*
 * generated by Xtext 2.15.0
 */
package ac.soton.java.whitespace.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class WhiteSpaceProposalProvider extends AbstractWhiteSpaceProposalProvider {
}
