/*
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.parser.antlr;

import ac.soton.java.whitespace.parser.antlr.internal.InternalWhiteSpaceParser;
import ac.soton.java.whitespace.services.WhiteSpaceGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class WhiteSpaceParser extends AbstractAntlrParser {

	@Inject
	private WhiteSpaceGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_NOTWS", "RULE_ML_COMMENT");
	}
	

	@Override
	protected InternalWhiteSpaceParser createParser(XtextTokenStream stream) {
		return new InternalWhiteSpaceParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "WSProgram";
	}

	public WhiteSpaceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WhiteSpaceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
