/*
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractWhiteSpaceValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage.eINSTANCE);
		return result;
	}
}
