/*
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.ui;

import ac.soton.java.whitespace.ui.internal.WhitespaceActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WhiteSpaceExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(WhitespaceActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		WhitespaceActivator activator = WhitespaceActivator.getInstance();
		return activator != null ? activator.getInjector(WhitespaceActivator.AC_SOTON_JAVA_WHITESPACE_WHITESPACE) : null;
	}

}
