/*
 * generated by Xtext 2.15.0
 */
package ac.soton.java.whitespace


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WhiteSpaceStandaloneSetup extends WhiteSpaceStandaloneSetupGenerated {

	def static void doSetup() {
		new WhiteSpaceStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
