/*
 * generated by Xtext 2.15.0
 */
package ac.soton.java.whitespace

import org.eclipse.xtext.conversion.IValueConverterService

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class WhiteSpaceRuntimeModule extends AbstractWhiteSpaceRuntimeModule {
	 override Class<? extends IValueConverterService> bindIValueConverterService() {
		return typeof(WhiteSpaceValueConverter);
	}

}
