/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>End Subroutine</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage#getEndSubroutine()
 * @model
 * @generated
 */
public interface EndSubroutine extends FlowControl
{
} // EndSubroutine
