/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Heap Access</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage#getHeapAccess()
 * @model
 * @generated
 */
public interface HeapAccess extends Statement
{
} // HeapAccess
