/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modulo</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage#getModulo()
 * @model
 * @generated
 */
public interface Modulo extends Arithmetic
{
} // Modulo
