/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Push</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.java.whitespace.whiteSpace.Push#getNumber <em>Number</em>}</li>
 * </ul>
 *
 * @see ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage#getPush()
 * @model
 * @generated
 */
public interface Push extends StackManipulation
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage#getPush_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link ac.soton.java.whitespace.whiteSpace.Push#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

} // Push
