/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Read Number</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage#getReadNumber()
 * @model
 * @generated
 */
public interface ReadNumber extends IO
{
} // ReadNumber
