/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
