/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unconditional Jump</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.java.whitespace.whiteSpace.UnconditionalJump#getLabel <em>Label</em>}</li>
 * </ul>
 *
 * @see ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage#getUnconditionalJump()
 * @model
 * @generated
 */
public interface UnconditionalJump extends FlowControl
{
  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage#getUnconditionalJump_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link ac.soton.java.whitespace.whiteSpace.UnconditionalJump#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

} // UnconditionalJump
