/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage
 * @generated
 */
public interface WhiteSpaceFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WhiteSpaceFactory eINSTANCE = ac.soton.java.whitespace.whiteSpace.impl.WhiteSpaceFactoryImpl.init();

  /**
   * Returns a new object of class '<em>WS Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>WS Program</em>'.
   * @generated
   */
  WSProgram createWSProgram();

  /**
   * Returns a new object of class '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  Statement createStatement();

  /**
   * Returns a new object of class '<em>Stack Manipulation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stack Manipulation</em>'.
   * @generated
   */
  StackManipulation createStackManipulation();

  /**
   * Returns a new object of class '<em>Push</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Push</em>'.
   * @generated
   */
  Push createPush();

  /**
   * Returns a new object of class '<em>Duplicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Duplicate</em>'.
   * @generated
   */
  Duplicate createDuplicate();

  /**
   * Returns a new object of class '<em>Copy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Copy</em>'.
   * @generated
   */
  Copy createCopy();

  /**
   * Returns a new object of class '<em>Swap</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Swap</em>'.
   * @generated
   */
  Swap createSwap();

  /**
   * Returns a new object of class '<em>Discard</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Discard</em>'.
   * @generated
   */
  Discard createDiscard();

  /**
   * Returns a new object of class '<em>Slide</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Slide</em>'.
   * @generated
   */
  Slide createSlide();

  /**
   * Returns a new object of class '<em>Arithmetic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arithmetic</em>'.
   * @generated
   */
  Arithmetic createArithmetic();

  /**
   * Returns a new object of class '<em>Addition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Addition</em>'.
   * @generated
   */
  Addition createAddition();

  /**
   * Returns a new object of class '<em>Subtraction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Subtraction</em>'.
   * @generated
   */
  Subtraction createSubtraction();

  /**
   * Returns a new object of class '<em>Multiplication</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multiplication</em>'.
   * @generated
   */
  Multiplication createMultiplication();

  /**
   * Returns a new object of class '<em>Division</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Division</em>'.
   * @generated
   */
  Division createDivision();

  /**
   * Returns a new object of class '<em>Modulo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Modulo</em>'.
   * @generated
   */
  Modulo createModulo();

  /**
   * Returns a new object of class '<em>Heap Access</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Heap Access</em>'.
   * @generated
   */
  HeapAccess createHeapAccess();

  /**
   * Returns a new object of class '<em>Store</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Store</em>'.
   * @generated
   */
  Store createStore();

  /**
   * Returns a new object of class '<em>Retrieve</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Retrieve</em>'.
   * @generated
   */
  Retrieve createRetrieve();

  /**
   * Returns a new object of class '<em>Flow Control</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flow Control</em>'.
   * @generated
   */
  FlowControl createFlowControl();

  /**
   * Returns a new object of class '<em>Mark Location</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mark Location</em>'.
   * @generated
   */
  MarkLocation createMarkLocation();

  /**
   * Returns a new object of class '<em>Call Subroutine</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Call Subroutine</em>'.
   * @generated
   */
  CallSubroutine createCallSubroutine();

  /**
   * Returns a new object of class '<em>Unconditional Jump</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unconditional Jump</em>'.
   * @generated
   */
  UnconditionalJump createUnconditionalJump();

  /**
   * Returns a new object of class '<em>Zero Jump</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Zero Jump</em>'.
   * @generated
   */
  ZeroJump createZeroJump();

  /**
   * Returns a new object of class '<em>Negative Jump</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Negative Jump</em>'.
   * @generated
   */
  NegativeJump createNegativeJump();

  /**
   * Returns a new object of class '<em>End Subroutine</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>End Subroutine</em>'.
   * @generated
   */
  EndSubroutine createEndSubroutine();

  /**
   * Returns a new object of class '<em>End Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>End Program</em>'.
   * @generated
   */
  EndProgram createEndProgram();

  /**
   * Returns a new object of class '<em>IO</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IO</em>'.
   * @generated
   */
  IO createIO();

  /**
   * Returns a new object of class '<em>Output Character</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Character</em>'.
   * @generated
   */
  OutputCharacter createOutputCharacter();

  /**
   * Returns a new object of class '<em>Output Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Number</em>'.
   * @generated
   */
  OutputNumber createOutputNumber();

  /**
   * Returns a new object of class '<em>Read Character</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Read Character</em>'.
   * @generated
   */
  ReadCharacter createReadCharacter();

  /**
   * Returns a new object of class '<em>Read Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Read Number</em>'.
   * @generated
   */
  ReadNumber createReadNumber();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  WhiteSpacePackage getWhiteSpacePackage();

} //WhiteSpaceFactory
