/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ac.soton.java.whitespace.whiteSpace.WhiteSpaceFactory
 * @model kind="package"
 * @generated
 */
public interface WhiteSpacePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "whiteSpace";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.soton.ac/java/whitespace/WhiteSpace";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "whiteSpace";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WhiteSpacePackage eINSTANCE = ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl.init();

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.WSProgramImpl <em>WS Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.WSProgramImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getWSProgram()
   * @generated
   */
  int WS_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WS_PROGRAM__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>WS Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WS_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.StatementImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.StackManipulationImpl <em>Stack Manipulation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.StackManipulationImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getStackManipulation()
   * @generated
   */
  int STACK_MANIPULATION = 2;

  /**
   * The number of structural features of the '<em>Stack Manipulation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STACK_MANIPULATION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.PushImpl <em>Push</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.PushImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getPush()
   * @generated
   */
  int PUSH = 3;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUSH__NUMBER = STACK_MANIPULATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Push</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUSH_FEATURE_COUNT = STACK_MANIPULATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.DuplicateImpl <em>Duplicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.DuplicateImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getDuplicate()
   * @generated
   */
  int DUPLICATE = 4;

  /**
   * The number of structural features of the '<em>Duplicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DUPLICATE_FEATURE_COUNT = STACK_MANIPULATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.CopyImpl <em>Copy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.CopyImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getCopy()
   * @generated
   */
  int COPY = 5;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPY__NUMBER = STACK_MANIPULATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Copy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPY_FEATURE_COUNT = STACK_MANIPULATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.SwapImpl <em>Swap</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.SwapImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getSwap()
   * @generated
   */
  int SWAP = 6;

  /**
   * The number of structural features of the '<em>Swap</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SWAP_FEATURE_COUNT = STACK_MANIPULATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.DiscardImpl <em>Discard</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.DiscardImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getDiscard()
   * @generated
   */
  int DISCARD = 7;

  /**
   * The number of structural features of the '<em>Discard</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISCARD_FEATURE_COUNT = STACK_MANIPULATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.SlideImpl <em>Slide</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.SlideImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getSlide()
   * @generated
   */
  int SLIDE = 8;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLIDE__NUMBER = STACK_MANIPULATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Slide</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLIDE_FEATURE_COUNT = STACK_MANIPULATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.ArithmeticImpl <em>Arithmetic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.ArithmeticImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getArithmetic()
   * @generated
   */
  int ARITHMETIC = 9;

  /**
   * The number of structural features of the '<em>Arithmetic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITHMETIC_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.AdditionImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 10;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = ARITHMETIC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.SubtractionImpl <em>Subtraction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.SubtractionImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getSubtraction()
   * @generated
   */
  int SUBTRACTION = 11;

  /**
   * The number of structural features of the '<em>Subtraction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACTION_FEATURE_COUNT = ARITHMETIC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.MultiplicationImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 12;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = ARITHMETIC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.DivisionImpl <em>Division</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.DivisionImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getDivision()
   * @generated
   */
  int DIVISION = 13;

  /**
   * The number of structural features of the '<em>Division</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVISION_FEATURE_COUNT = ARITHMETIC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.ModuloImpl <em>Modulo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.ModuloImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getModulo()
   * @generated
   */
  int MODULO = 14;

  /**
   * The number of structural features of the '<em>Modulo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULO_FEATURE_COUNT = ARITHMETIC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.HeapAccessImpl <em>Heap Access</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.HeapAccessImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getHeapAccess()
   * @generated
   */
  int HEAP_ACCESS = 15;

  /**
   * The number of structural features of the '<em>Heap Access</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEAP_ACCESS_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.StoreImpl <em>Store</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.StoreImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getStore()
   * @generated
   */
  int STORE = 16;

  /**
   * The number of structural features of the '<em>Store</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_FEATURE_COUNT = HEAP_ACCESS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.RetrieveImpl <em>Retrieve</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.RetrieveImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getRetrieve()
   * @generated
   */
  int RETRIEVE = 17;

  /**
   * The number of structural features of the '<em>Retrieve</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE_FEATURE_COUNT = HEAP_ACCESS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.FlowControlImpl <em>Flow Control</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.FlowControlImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getFlowControl()
   * @generated
   */
  int FLOW_CONTROL = 18;

  /**
   * The number of structural features of the '<em>Flow Control</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOW_CONTROL_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.MarkLocationImpl <em>Mark Location</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.MarkLocationImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getMarkLocation()
   * @generated
   */
  int MARK_LOCATION = 19;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARK_LOCATION__LABEL = FLOW_CONTROL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Mark Location</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARK_LOCATION_FEATURE_COUNT = FLOW_CONTROL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.CallSubroutineImpl <em>Call Subroutine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.CallSubroutineImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getCallSubroutine()
   * @generated
   */
  int CALL_SUBROUTINE = 20;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_SUBROUTINE__LABEL = FLOW_CONTROL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Call Subroutine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_SUBROUTINE_FEATURE_COUNT = FLOW_CONTROL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.UnconditionalJumpImpl <em>Unconditional Jump</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.UnconditionalJumpImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getUnconditionalJump()
   * @generated
   */
  int UNCONDITIONAL_JUMP = 21;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNCONDITIONAL_JUMP__LABEL = FLOW_CONTROL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Unconditional Jump</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNCONDITIONAL_JUMP_FEATURE_COUNT = FLOW_CONTROL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.ZeroJumpImpl <em>Zero Jump</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.ZeroJumpImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getZeroJump()
   * @generated
   */
  int ZERO_JUMP = 22;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZERO_JUMP__LABEL = FLOW_CONTROL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Zero Jump</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZERO_JUMP_FEATURE_COUNT = FLOW_CONTROL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.NegativeJumpImpl <em>Negative Jump</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.NegativeJumpImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getNegativeJump()
   * @generated
   */
  int NEGATIVE_JUMP = 23;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATIVE_JUMP__LABEL = FLOW_CONTROL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Negative Jump</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATIVE_JUMP_FEATURE_COUNT = FLOW_CONTROL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.EndSubroutineImpl <em>End Subroutine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.EndSubroutineImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getEndSubroutine()
   * @generated
   */
  int END_SUBROUTINE = 24;

  /**
   * The number of structural features of the '<em>End Subroutine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_SUBROUTINE_FEATURE_COUNT = FLOW_CONTROL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.EndProgramImpl <em>End Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.EndProgramImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getEndProgram()
   * @generated
   */
  int END_PROGRAM = 25;

  /**
   * The number of structural features of the '<em>End Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_PROGRAM_FEATURE_COUNT = FLOW_CONTROL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.IOImpl <em>IO</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.IOImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getIO()
   * @generated
   */
  int IO = 26;

  /**
   * The number of structural features of the '<em>IO</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IO_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.OutputCharacterImpl <em>Output Character</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.OutputCharacterImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getOutputCharacter()
   * @generated
   */
  int OUTPUT_CHARACTER = 27;

  /**
   * The number of structural features of the '<em>Output Character</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_CHARACTER_FEATURE_COUNT = IO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.OutputNumberImpl <em>Output Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.OutputNumberImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getOutputNumber()
   * @generated
   */
  int OUTPUT_NUMBER = 28;

  /**
   * The number of structural features of the '<em>Output Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_NUMBER_FEATURE_COUNT = IO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.ReadCharacterImpl <em>Read Character</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.ReadCharacterImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getReadCharacter()
   * @generated
   */
  int READ_CHARACTER = 29;

  /**
   * The number of structural features of the '<em>Read Character</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_CHARACTER_FEATURE_COUNT = IO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ac.soton.java.whitespace.whiteSpace.impl.ReadNumberImpl <em>Read Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.whitespace.whiteSpace.impl.ReadNumberImpl
   * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getReadNumber()
   * @generated
   */
  int READ_NUMBER = 30;

  /**
   * The number of structural features of the '<em>Read Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_NUMBER_FEATURE_COUNT = IO_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.WSProgram <em>WS Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>WS Program</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.WSProgram
   * @generated
   */
  EClass getWSProgram();

  /**
   * Returns the meta object for the containment reference list '{@link ac.soton.java.whitespace.whiteSpace.WSProgram#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.WSProgram#getStatements()
   * @see #getWSProgram()
   * @generated
   */
  EReference getWSProgram_Statements();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.StackManipulation <em>Stack Manipulation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stack Manipulation</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.StackManipulation
   * @generated
   */
  EClass getStackManipulation();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Push <em>Push</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Push</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Push
   * @generated
   */
  EClass getPush();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.whitespace.whiteSpace.Push#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Push#getNumber()
   * @see #getPush()
   * @generated
   */
  EAttribute getPush_Number();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Duplicate <em>Duplicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Duplicate</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Duplicate
   * @generated
   */
  EClass getDuplicate();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Copy <em>Copy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Copy</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Copy
   * @generated
   */
  EClass getCopy();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.whitespace.whiteSpace.Copy#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Copy#getNumber()
   * @see #getCopy()
   * @generated
   */
  EAttribute getCopy_Number();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Swap <em>Swap</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Swap</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Swap
   * @generated
   */
  EClass getSwap();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Discard <em>Discard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Discard</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Discard
   * @generated
   */
  EClass getDiscard();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Slide <em>Slide</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Slide</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Slide
   * @generated
   */
  EClass getSlide();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.whitespace.whiteSpace.Slide#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Slide#getNumber()
   * @see #getSlide()
   * @generated
   */
  EAttribute getSlide_Number();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Arithmetic <em>Arithmetic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arithmetic</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Arithmetic
   * @generated
   */
  EClass getArithmetic();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Subtraction <em>Subtraction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subtraction</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Subtraction
   * @generated
   */
  EClass getSubtraction();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Division <em>Division</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Division</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Division
   * @generated
   */
  EClass getDivision();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Modulo <em>Modulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modulo</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Modulo
   * @generated
   */
  EClass getModulo();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.HeapAccess <em>Heap Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Heap Access</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.HeapAccess
   * @generated
   */
  EClass getHeapAccess();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Store <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Store
   * @generated
   */
  EClass getStore();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.Retrieve <em>Retrieve</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Retrieve</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.Retrieve
   * @generated
   */
  EClass getRetrieve();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.FlowControl <em>Flow Control</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flow Control</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.FlowControl
   * @generated
   */
  EClass getFlowControl();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.MarkLocation <em>Mark Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mark Location</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.MarkLocation
   * @generated
   */
  EClass getMarkLocation();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.whitespace.whiteSpace.MarkLocation#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.MarkLocation#getLabel()
   * @see #getMarkLocation()
   * @generated
   */
  EAttribute getMarkLocation_Label();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.CallSubroutine <em>Call Subroutine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Call Subroutine</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.CallSubroutine
   * @generated
   */
  EClass getCallSubroutine();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.whitespace.whiteSpace.CallSubroutine#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.CallSubroutine#getLabel()
   * @see #getCallSubroutine()
   * @generated
   */
  EAttribute getCallSubroutine_Label();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.UnconditionalJump <em>Unconditional Jump</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unconditional Jump</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.UnconditionalJump
   * @generated
   */
  EClass getUnconditionalJump();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.whitespace.whiteSpace.UnconditionalJump#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.UnconditionalJump#getLabel()
   * @see #getUnconditionalJump()
   * @generated
   */
  EAttribute getUnconditionalJump_Label();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.ZeroJump <em>Zero Jump</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Zero Jump</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.ZeroJump
   * @generated
   */
  EClass getZeroJump();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.whitespace.whiteSpace.ZeroJump#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.ZeroJump#getLabel()
   * @see #getZeroJump()
   * @generated
   */
  EAttribute getZeroJump_Label();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.NegativeJump <em>Negative Jump</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Negative Jump</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.NegativeJump
   * @generated
   */
  EClass getNegativeJump();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.whitespace.whiteSpace.NegativeJump#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.NegativeJump#getLabel()
   * @see #getNegativeJump()
   * @generated
   */
  EAttribute getNegativeJump_Label();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.EndSubroutine <em>End Subroutine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End Subroutine</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.EndSubroutine
   * @generated
   */
  EClass getEndSubroutine();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.EndProgram <em>End Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End Program</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.EndProgram
   * @generated
   */
  EClass getEndProgram();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.IO <em>IO</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IO</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.IO
   * @generated
   */
  EClass getIO();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.OutputCharacter <em>Output Character</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output Character</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.OutputCharacter
   * @generated
   */
  EClass getOutputCharacter();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.OutputNumber <em>Output Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output Number</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.OutputNumber
   * @generated
   */
  EClass getOutputNumber();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.ReadCharacter <em>Read Character</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Read Character</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.ReadCharacter
   * @generated
   */
  EClass getReadCharacter();

  /**
   * Returns the meta object for class '{@link ac.soton.java.whitespace.whiteSpace.ReadNumber <em>Read Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Read Number</em>'.
   * @see ac.soton.java.whitespace.whiteSpace.ReadNumber
   * @generated
   */
  EClass getReadNumber();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WhiteSpaceFactory getWhiteSpaceFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.WSProgramImpl <em>WS Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.WSProgramImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getWSProgram()
     * @generated
     */
    EClass WS_PROGRAM = eINSTANCE.getWSProgram();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WS_PROGRAM__STATEMENTS = eINSTANCE.getWSProgram_Statements();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.StatementImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.StackManipulationImpl <em>Stack Manipulation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.StackManipulationImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getStackManipulation()
     * @generated
     */
    EClass STACK_MANIPULATION = eINSTANCE.getStackManipulation();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.PushImpl <em>Push</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.PushImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getPush()
     * @generated
     */
    EClass PUSH = eINSTANCE.getPush();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PUSH__NUMBER = eINSTANCE.getPush_Number();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.DuplicateImpl <em>Duplicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.DuplicateImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getDuplicate()
     * @generated
     */
    EClass DUPLICATE = eINSTANCE.getDuplicate();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.CopyImpl <em>Copy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.CopyImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getCopy()
     * @generated
     */
    EClass COPY = eINSTANCE.getCopy();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COPY__NUMBER = eINSTANCE.getCopy_Number();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.SwapImpl <em>Swap</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.SwapImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getSwap()
     * @generated
     */
    EClass SWAP = eINSTANCE.getSwap();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.DiscardImpl <em>Discard</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.DiscardImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getDiscard()
     * @generated
     */
    EClass DISCARD = eINSTANCE.getDiscard();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.SlideImpl <em>Slide</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.SlideImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getSlide()
     * @generated
     */
    EClass SLIDE = eINSTANCE.getSlide();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SLIDE__NUMBER = eINSTANCE.getSlide_Number();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.ArithmeticImpl <em>Arithmetic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.ArithmeticImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getArithmetic()
     * @generated
     */
    EClass ARITHMETIC = eINSTANCE.getArithmetic();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.AdditionImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.SubtractionImpl <em>Subtraction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.SubtractionImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getSubtraction()
     * @generated
     */
    EClass SUBTRACTION = eINSTANCE.getSubtraction();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.MultiplicationImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.DivisionImpl <em>Division</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.DivisionImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getDivision()
     * @generated
     */
    EClass DIVISION = eINSTANCE.getDivision();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.ModuloImpl <em>Modulo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.ModuloImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getModulo()
     * @generated
     */
    EClass MODULO = eINSTANCE.getModulo();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.HeapAccessImpl <em>Heap Access</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.HeapAccessImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getHeapAccess()
     * @generated
     */
    EClass HEAP_ACCESS = eINSTANCE.getHeapAccess();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.StoreImpl <em>Store</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.StoreImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getStore()
     * @generated
     */
    EClass STORE = eINSTANCE.getStore();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.RetrieveImpl <em>Retrieve</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.RetrieveImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getRetrieve()
     * @generated
     */
    EClass RETRIEVE = eINSTANCE.getRetrieve();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.FlowControlImpl <em>Flow Control</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.FlowControlImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getFlowControl()
     * @generated
     */
    EClass FLOW_CONTROL = eINSTANCE.getFlowControl();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.MarkLocationImpl <em>Mark Location</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.MarkLocationImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getMarkLocation()
     * @generated
     */
    EClass MARK_LOCATION = eINSTANCE.getMarkLocation();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MARK_LOCATION__LABEL = eINSTANCE.getMarkLocation_Label();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.CallSubroutineImpl <em>Call Subroutine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.CallSubroutineImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getCallSubroutine()
     * @generated
     */
    EClass CALL_SUBROUTINE = eINSTANCE.getCallSubroutine();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALL_SUBROUTINE__LABEL = eINSTANCE.getCallSubroutine_Label();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.UnconditionalJumpImpl <em>Unconditional Jump</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.UnconditionalJumpImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getUnconditionalJump()
     * @generated
     */
    EClass UNCONDITIONAL_JUMP = eINSTANCE.getUnconditionalJump();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNCONDITIONAL_JUMP__LABEL = eINSTANCE.getUnconditionalJump_Label();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.ZeroJumpImpl <em>Zero Jump</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.ZeroJumpImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getZeroJump()
     * @generated
     */
    EClass ZERO_JUMP = eINSTANCE.getZeroJump();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZERO_JUMP__LABEL = eINSTANCE.getZeroJump_Label();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.NegativeJumpImpl <em>Negative Jump</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.NegativeJumpImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getNegativeJump()
     * @generated
     */
    EClass NEGATIVE_JUMP = eINSTANCE.getNegativeJump();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NEGATIVE_JUMP__LABEL = eINSTANCE.getNegativeJump_Label();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.EndSubroutineImpl <em>End Subroutine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.EndSubroutineImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getEndSubroutine()
     * @generated
     */
    EClass END_SUBROUTINE = eINSTANCE.getEndSubroutine();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.EndProgramImpl <em>End Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.EndProgramImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getEndProgram()
     * @generated
     */
    EClass END_PROGRAM = eINSTANCE.getEndProgram();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.IOImpl <em>IO</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.IOImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getIO()
     * @generated
     */
    EClass IO = eINSTANCE.getIO();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.OutputCharacterImpl <em>Output Character</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.OutputCharacterImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getOutputCharacter()
     * @generated
     */
    EClass OUTPUT_CHARACTER = eINSTANCE.getOutputCharacter();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.OutputNumberImpl <em>Output Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.OutputNumberImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getOutputNumber()
     * @generated
     */
    EClass OUTPUT_NUMBER = eINSTANCE.getOutputNumber();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.ReadCharacterImpl <em>Read Character</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.ReadCharacterImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getReadCharacter()
     * @generated
     */
    EClass READ_CHARACTER = eINSTANCE.getReadCharacter();

    /**
     * The meta object literal for the '{@link ac.soton.java.whitespace.whiteSpace.impl.ReadNumberImpl <em>Read Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.whitespace.whiteSpace.impl.ReadNumberImpl
     * @see ac.soton.java.whitespace.whiteSpace.impl.WhiteSpacePackageImpl#getReadNumber()
     * @generated
     */
    EClass READ_NUMBER = eINSTANCE.getReadNumber();

  }

} //WhiteSpacePackage
