/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.whiteSpace;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>WS Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.java.whitespace.whiteSpace.WSProgram#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage#getWSProgram()
 * @model
 * @generated
 */
public interface WSProgram extends EObject
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link ac.soton.java.whitespace.whiteSpace.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see ac.soton.java.whitespace.whiteSpace.WhiteSpacePackage#getWSProgram_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // WSProgram
