/*
 * generated by Xtext 2.27.0
 */
package ac.soton.java.whitespace.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWhiteSpaceScopeProvider extends DelegatingScopeProvider {
}
